branches:
  except:
    gh-pages

language: c
dist: trusty
sudo: required

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:webkit-team/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y --allow-unauthenticated --no-install-recommends libwebkit2gtk-4.0-dev

script: make options && make -j test
